### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by jgthornburgh** [And3rsL/Deebot-for-Home-Assistant#104]
**Describe the bug**
When trying to add the new integration I get "Config flow could not be loaded"

**Configuration.yaml**
Deleted & restarted before trying to add the integration

**System Informations:**
 - Device: [Deebot ozmo 920]
 - Home Assistant Version: supervisor-2021.04.0, core-2021.4.6
 - Hardware: Proxmox

**Logs**
2021-04-26 08:54:40 INFO (SyncWorker_3) [homeassistant.util.package] Attempting install of deebotozmo==1.8.0

**Comment by edenhaus** [comment]
Do you have a stable internet connection?
Do you have more logs? Can the dependency be successfully be installed?

**Comment by edenhaus** [comment]
Closing as no information was provided
