### ISSUE TITLE
after updating to 2.1.1 the sensors are no longer updated

### ISSUE THREAD

**Issue by mamos76** [And3rsL/Deebot-for-Home-Assistant#115]
**Describe the bug**
Since I updated to version 2.1.1 the sensors are no longer updated by the integration. The only sensors that keep updating are those of the battery status and that of the suction speed level. The commands to the roboot all work correctly. To update the sensors I have to restart the Home assistant every time.
With the version before breaking changes everything worked correctly

Completely deleted configuration from configuration.yaml

**System Informations:**
 - Device: ozmo T8
 - Home Assistant Version: 2021.5.1
 - Hardware: proxmox 
 - Home Assistant Installation: Hassio core 2021.5.1 supervisor 2021.4.3

**Comment by jeremeyi** [comment]
I'm seeing the same issue battery sensor updates, but others such as area cleaned and time cleaned are not updated, restarting HA  updates those sensors but they won't refresh unless HA is restarted again.

**Comment by edenhaus** [comment]
Can one or better both of you activate debug logs and attach them here. More details https://github.com/And3rsL/Deebot-for-Hassio#issues

I have an idea, where the problem can be, but I need more information to be sure.

Before attaching the logs here please filter out logs from other components and also confidential data (token, password,...)

**Comment by mamos76** [comment]
> Can one or better both of you activate debug logs and attach them here. More details https://github.com/And3rsL/Deebot-for-Hassio#issues
> 
> I have an idea, where the problem can be, but I need more information to be sure.
> 
> Before attaching the logs here please filter out logs from other components and also confidential data (token, password,...)


I tried to insert in the configuration.yam:

logger:
  logs:
    homeassistant.components.deebot: debug
    homeassistant.components.vacuum.deebotozmo: debug
    deebotozmo: debug

but it creates me a file of more than 110 MB and I don't know how to filter only what concerns the integration of deboot

**Comment by Gino1606** [comment]
I have the same problem too
by @mamos76 on ozmo 920. the robot responds to commands, but the sensors do not update. I downgraded to version 2.0.1 and it works again. Do you have any idea what that might be?

**Comment by edenhaus** [comment]
> > Can one or better both of you activate debug logs and attach them here. More details https://github.com/And3rsL/Deebot-for-Hassio#issues
> > I have an idea, where the problem can be, but I need more information to be sure.
> > Before attaching the logs here please filter out logs from other components and also confidential data (token, password,...)
> 
> I tried to insert in the configuration.yam:
> 
> logger:
> logs:
> homeassistant.components.deebot: debug
> homeassistant.components.vacuum.deebotozmo: debug
> deebotozmo: debug
> 
> but it creates me a file of more than 110 MB and I don't know how to filter only what concerns the integration of deboot

Use tools like https://onlinestringtools.com/filter-string to filter out lines. We are interested on all logs of the loggers:
- homeassistant.components.deebot
- homeassistant.components.vacuum.deebotozmo
- deebotozmo

**Comment by jeremeyi** [comment]
I forgot to mention that my vacuum starts a cleaning job at 2:00pm and runs for about an hour if that helps. 
    On Wednesday, May 12, 2021, 04:05:41 PM CDT, Robert Resch ***@***.***> wrote:  
 
 




Can one or better both of you activate debug logs and attach them here. More details https://github.com/And3rsL/Deebot-for-Hassio#issues
I have an idea, where the problem can be, but I need more information to be sure.
Before attaching the logs here please filter out logs from other components and also confidential data (token, password,...)


I tried to insert in the configuration.yam:

logger:
logs:
homeassistant.components.deebot: debug
homeassistant.components.vacuum.deebotozmo: debug
deebotozmo: debug

but it creates me a file of more than 110 MB and I don't know how to filter only what concerns the integration of deboot


Use tools like https://onlinestringtools.com/filter-string to filter out lines. We are interested on all logs of the loggers:
   
   - homeassistant.components.deebot
   - homeassistant.components.vacuum.deebotozmo
   - deebotozmo

**Comment by jeremeyi** [comment]
I didn't get any results from homeassistant.components.vacuum.deebotozmo.  But the other two I did and have attached as two separate text files with the name representing the corresponding filter (I used notepad++ and couldn't figure out how to do both at once).  If it helps at all my vacuum starts a cleaning job at 2:00pm and runs for about an hour.   If I need to attach the logs differently let me know. 

    On Wednesday, May 12, 2021, 04:05:41 PM CDT, Robert Resch ***@***.***> wrote:  
 
 




Can one or better both of you activate debug logs and attach them here. More details https://github.com/And3rsL/Deebot-for-Hassio#issues
I have an idea, where the problem can be, but I need more information to be sure.
Before attaching the logs here please filter out logs from other components and also confidential data (token, password,...)


I tried to insert in the configuration.yam:

logger:
logs:
homeassistant.components.deebot: debug
homeassistant.components.vacuum.deebotozmo: debug
deebotozmo: debug

but it creates me a file of more than 110 MB and I don't know how to filter only what concerns the integration of deboot


Use tools like https://onlinestringtools.com/filter-string to filter out lines. We are interested on all logs of the loggers:
   
   - homeassistant.components.deebot
   - homeassistant.components.vacuum.deebotozmo
   - deebotozmo

**Comment by jeremeyi** [comment]
[logs.zip](https://github.com/And3rsL/Deebot-for-Hassio/files/6469642/logs.zip)

**Comment by edenhaus** [comment]
Thanks for the logs, I was able to reproduce…. The bug is not trivial so it will take some time to fix it. Strange is that my personal setup is not affected

**Comment by edenhaus** [comment]
Sometimes you think to complicate :see_no_evil:
I released a beta with the fix. Can someone please test it and give feedback if the issue has be solved.

**Comment by Gino1606** [comment]
@edenhaus I have it installed and it works perfectly now. Indeed you have also corrected the graphic part of the installation. You did a great job 🔝💪 congratulations and thanks😊
