### ISSUE TITLE
Problem with livemap

### ISSUE THREAD

**Issue by Friedrieck** [And3rsL/Deebot-for-Home-Assistant#118]
I just installed your integration few days ago, and first of all, a big thank you! The official Ecovacs integration is strangely abandoned, so thank you very much for your efforts!

**Describe the bug**
From time to time, the livemap image does not look OK, it seems really oversized, with the actual map shrinked in the bottom left corner of the image.

**Configuration.yaml (Remember to delete your credentials)**
N/A (config flow now)
**Screenshots**
![livemap](https://user-images.githubusercontent.com/12567014/118377545-301c8d00-b5ce-11eb-8d6a-4a6fd826f31c.jpg)

**System Informations:**
 - Device: DEEBOT OZMO T8+
## System Health

version | core-2021.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.109
arch | x86_64
timezone | Europe/Brussels

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4890
Installed Version | 1.12.3
Stage | running
Available Repositories | 820
Installed Repositories | 32

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.3
docker_version | 19.03.15
disk_total | 62.3 GB
disk_used | 31.7 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.1), File editor (5.3.0), Check Home Assistant configuration (3.7.1), SSH & Web Terminal (8.2.1), Visual Studio Code (3.3.1), SONOS AudioClip TTS (2.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 17
views | 8
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Additional context**
It may got fixed (normal map gets back), but then it reappears. 

**Logs**
Does not seem useful, but let me know otherwise.

**Comment by illivanillie** [comment]
Same here! But I do not see a 'fixed' map, only the tiny one in the corner with lines from the corner to the map.
Cam state is idle permanently. Don’t know if this is any helpful. 
If you need any information, just tell me.
Greetings!

**Comment by illivanillie** [comment]
I just noticed that the map is colored when the map is small in the corner.
Since the update I cannot find a way to change the settings. Is there? I would disable colored map for now and see from there

**Comment by edenhaus** [comment]
> I just noticed that the map is colored when the map is small in the corner.
> Since the update I cannot find a way to change the settings. Is there? I would disable colored map for now and see from there

Currently there is no easy way to disable it.
You have two options:
- Delete the integration and setup it again via UI
- Modify the internal json file, where the configuration is stored. (Only for advanced users) I don't write here now the exact file as advanced users already know, where config entries are stored and normal user should not use this way as it can destroy your whole home assistant configuration.

Please also note that we will remove the colored rooms with the next update as it is not working correctly. See https://github.com/And3rsL/Deebotozmo/pull/29

@Friedrieck Can you confirm that this issue exists only, when the option "Draw rooms" is activated?

**Comment by Friedrieck** [comment]
Hi @edenhaus ,
Sorry for the delay in responding, I wanted to test first.
So, I removed the integration, put it back without the colour map beta setting, started and achieved a cleaning, and all is fine, no more problem with the map! The live map is OK, with the drawing of the deboot's path.
