### ISSUE TITLE
Incompatible with DeeBot Ozmo 930

### ISSUE THREAD

**Issue by Micha95** [And3rsL/Deebot-for-Home-Assistant#123]
Hello,
It seems, as it is absolutely incompatible with Deebot Ozmo 930.
with this addon: https://github.com/Ligio/hacc-ozmo i can at least send commands to the Deebot, with Deebot-for-Home-Assistant, i only get unavailable, not matter if it is the sensors, or the vaccum itself.

Dont know why, but this is kinda strange issue.
(regarding logs, login is successfull and it detects the Deebot, but it simply says, that it is unavailable all the time)

**Comment by edenhaus** [comment]
Your robot uses MQTT/XML and we are only supporting MQTT/JSON.
See #35
