### ISSUE TITLE
Reduce the amount of requests - Polling

### ISSUE THREAD

**Issue by sefki21** [And3rsL/Deebot-for-Home-Assistant#127]
Hi @And3rsL 

I read other threads about polling issues but they are closed (apprently fixed in 2.1.1).

Sadly I reach 15'000 polling in 24h to portla-na.ecouser.net still with 2.1.1. I own 2 Ecovacs T9, map is disabled.  

Do I need to adjust something?

**Comment by edenhaus** [comment]
Currently you can't change the polling interval.

But I have started to refactor the whole component and afterwards I add the functionality to subscribe to events send out by the robot. It will take some time as I'm very busy this month....

**Comment by edenhaus** [comment]
I released a pre-release of the upcoming version, which reduces the polling...
This custom component subscribes to the events send out by the robot over mqtt. Only during starting of HA all information will be polled, afterwards only the lifespan (brush, heap stats) will be pooled each minute.
Maybe I have also a solution for that to reduce it a little bit more... (https://github.com/And3rsL/Deebotozmo/discussions/35) Please feel free to add also your ideas

**Comment by sefki21** [comment]
great thank you! seems to be fine now.
