### ISSUE TITLE
Constant DNS attempts

### ISSUE THREAD

**Issue by aidbish** [And3rsL/Deebot-for-Home-Assistant#129]
**Describe the bug**
Integration has just started recently doing continous dns requests to portal-eu.ecouser.net
Adguard is logging around 2 or 3 a second

**Configuration.yaml (Remember to delete your credentials)**
```
Using config_flow setup. 
Country; au
Continent: eu


**Screenshots**
![image](https://user-images.githubusercontent.com/38182386/120951584-8a071180-c78c-11eb-9643-ec8b449863d3.png)


**System Informations:**
 - Device: [Deebot ozmo 920
 - Home Assistant Version: 2021.6.2 .
 - Hardware: Server.
 - Home Assistant Installation: Linux HA Container

**Additional context**

i have attempted to uninstall and reisntall and this doesnt make any difference


**Logs**
Please add full home_assistant.log filtered on [deebotozmo]

**Comment by edenhaus** [comment]
Currently we are polling all information (some requests every few seconds). See #127
We use the library `requests` to perform our requests. Have you changed something in your network or can you provide us with more information?

**Comment by aidbish** [comment]
Hi @edenhaus 
thanks for getting back to me
The only change i have made is to install Adguard, this is what exposed the DNS requests to me, so not sure how long this has been happening
No requests are blocked just they are just constant
I have tried disabling the Adguard filters to check, but the requests still occur.

**Comment by edenhaus** [comment]
I guess Adguard is not allowing to cache dns entries, so adguard has the possibility to log each requests. As a lot of refactoring is done in #125, which will be merged soon. I will close this issue in favor of #127 as it has to do with the polling.

Duplicate #127
