### ISSUE TITLE
HA Reboot on cleaning start

### ISSUE THREAD

**Issue by bluesheep** [And3rsL/Deebot-for-Home-Assistant#131]
**Describe the bug**
Every time my vacuum starts a clean, The core of home assistant crashes and restarts. There is no evidence of this in any logs that I can find, other than a restart showing in the main log. Happens both on scheduled cleans (initiated in app) and when I start a clean using a service call.

Before the clean, HA correctly reports device status. After rebooting, HA correctly display maps and state of the robot. 

**Screenshots**
N/A

**System Informations:**

Device: Deebot Ozmo 920
Home Assistant Version: core-2021.6.3
Hardware: Raspberry Pi 3b
Home Assistant Installation: hassio
**Additional context**

**Logs**
Can provide, but is just a standard startup.

**Comment by edenhaus** [comment]
HA is deleting the log file at startup. We need the logs before HA is restarting, unfortunately I don't know how you can get it. Probably we need to google if there is a solution for that. Without logs we cannot help you :(

**Comment by And3rsL** [comment]
Please try to disable livemap and test it again

Pi 3b seems is not powerfull enough to handle it

**Comment by edenhaus** [comment]
Closing due inactivity
