### ISSUE TITLE
Deebot Integration not available

### ISSUE THREAD

**Issue by illivanillie** [And3rsL/Deebot-for-Home-Assistant#132]
For me there is no deebot integration available in Home assistant. Was about to reinstall.

**Comment by edenhaus** [comment]
Can you please add your logs. Did HA successfully install and setup the integration?

**Comment by illivanillie** [comment]
When you look https://www.home-assistant.io/integrations/ here, there is no deebot for HA. Same in my system, will post details later

**Comment by edenhaus** [comment]
@illivanillie this is a custom component, you need install it via HACS. After you have install it, you can find it under integrations on your system. As it is a custom component it will never be on  https://www.home-assistant.io/integrations/

**Comment by illivanillie** [comment]
Then this 
„To add your Ecovacs devices into your Home Assistant installation, follow the steps in Home Assistant -> Settings -> Integration -> Add -> Deebot for Home Assistant“
is confusing.

**Comment by edenhaus** [comment]
I will add "After installation"
