### ISSUE TITLE
Version 3.0.0b1 tries to connect to wrong URL

### ISSUE THREAD

**Issue by hanlongwang** [And3rsL/Deebot-for-Home-Assistant#133]
Version 3.0.0b1 tries to connect to portal-us.ecouser.net instead of portal-na.ecouser.net, giving unknown host errors

**Comment by edenhaus** [comment]
What‘s your configuration?

**Comment by edenhaus** [comment]
I released a new beta version right now, can you please test it. If the bug was fixed, please close this issue :)

**Comment by hanlongwang** [comment]
Looks good now, thanks!
