### ISSUE TITLE
iPhone App Deebot N8 +  keeps showing Ghost areas. overlaid on original Map

### ISSUE THREAD

**Issue by TomBrandt** [And3rsL/Deebot-for-Home-Assistant#141]
The Live Map would have a ghost image showing overlaid on original Map and the Deebot would try and follow that. After removing creating new map. Same issue happened. Uninstalled Deebot for Home Assistant problem hasn't returned.

**Comment by illivanillie** [comment]
Unfortunately this is a common ecovacs problem. It’s given me headaches too..
See [here](https://www.ecovacs.com/us/support/DEEBOT-N8-PRO/faq-detail?id=292&product_id=59)
