### ISSUE TITLE
can't find my deebot t8 max

### ISSUE THREAD

**Issue by tianlong1266** [And3rsL/Deebot-for-Home-Assistant#142]
**Describe the bug**
can't find my deebot t8 max.
i'm install deetbot for home assistant in hacs, and then i add an intergrations for deebot for home assistant. i can input my username,password and some messanges,and then i click the next button, it let me to choose a robot,but there are no robot i can choose.

**Configuration.yaml (Remember to delete your credentials)**
# required fields
deebot:
  username: ECNNY***
  password: ******
  country: cn
  continent: as
  deviceid:
    E0BG14**************
  # Optional
  live_map: True                    # Enable Live Map.. may cause issues on low power hardware | Default: True
  show_color_rooms: False           # Enable draw room colors as in the app.. BE Carefull, very experimental. first thing to disable if there is any issue | Default: False
  livemappath: 'www/'   # Path where to save live_map (Each bot will have XXX_liveMap.png where XXX is the vacbot name)
vacuum:
  - platform: deebot
    username: YOUR_ECOVACS_USERNAME
    password: YOUR_ECOVACS_PASSWORD
    country: YOUR_TWO_LETTER_COUNTRY_CODE
    continent: YOUR_TWO_LETTER_CONTINENT_CODE
    deviceid: YOUR_ROBOT_ID
```

**Screenshots**
If applicable, add screenshots to help explain your problem.
![Uploading image.png…]()


**System Informations:**
 - Device:deebot t8 max
 - Home Assistant Version: 2021.6.5
 - Hardware: Raspberry 4b
 - Home Assistant Installation: homeassistant OS

**Additional context**
Add any other context about the problem here.

**Logs**
Please add full home_assistant.log filtered on [deebotozmo]

**Comment by 735473216** [comment]
Maybe you can find suggestion from my [issue](https://github.com/And3rsL/Deebotozmo/issues/30)
t8max must be similar with t9max , i guess. :)

**Comment by horacecar** [comment]
I also cannot find my t5 max device

**Comment by edenhaus** [comment]
As we only have the Ozmo 950, we can only debug this model correctly. See #35

You need probably sniff the traffic between the app and the ecovacs servers and see if there are differences.
