### ISSUE TITLE
last_clean_image never update

### ISSUE THREAD

**Issue by michelebossa** [And3rsL/Deebot-for-Home-Assistant#149]
**Describe the bug**
Hi,
I have a problem with last_clean_image sensor from 2/3 days ago i never revive a change of status value i have tried to reboot HA but don't FIX

**Screenshots**
![image](https://user-images.githubusercontent.com/38975058/124452651-ddb64c00-dd86-11eb-9556-44508c5d314a.png)

**System Informations:**
 - Device: Deebot ozmo 920
 - Home Assistant Version: 2021.6.6
 - Hardware: Raspberry
 - Home Assistant Installation: Linux

**Logs**
no error found into log

**Comment by michelebossa** [comment]
Today the sensor it is restarted to change after cleaning of rooms. I have just update the HA at the last release. 
I don't think it is related but it is a very strange situation. Maybe it is related on cloud of ECOVACS. I'm waiting some days to check if now it is all ok and after I'll close these issue

**Comment by michelebossa** [comment]
the problem it is occurs again two days no sensor update after cleaning.
I think there is some trouble maybe somebody can investigate.

Thanks.

**Comment by edenhaus** [comment]
Can you please provide us logs and also which version of the integration are you using?

**Comment by michelebossa** [comment]
Hi @edenhaus,
This morning i have checked and maybe i have understand why there is this problem, maybe it is something related to ECOVACS cloud.

I have made a cleaning today 17/07/2021 (screenshot of notify inside APP)
![image](https://user-images.githubusercontent.com/38975058/126034134-9e36d8b9-571b-4ac3-9422-ffe25a2982aa.png)
The sensor i think retrieve information from "Cleaning records" section of APP
![image](https://user-images.githubusercontent.com/38975058/126034167-c99861ce-0cbd-454f-8fae-b7e1966fede8.png)

There is no row with today cleaning it was a BUG of ECOVACS Cloud? The sensor retrieve the information from this section of app?

I have the version 2.1.2 of custom component and i have stored the log it is about 2MB if you need i can send to a mail.

If it is confirmed maybe i can open a ticket to ECOVASH support.

Thanks.

**Comment by edenhaus** [comment]
As I don't use the ecovacs cloud, I cannot confirm the issue.
Also please not that this component has nothing to do with ecovacs and also they don't support it...

**Comment by michelebossa** [comment]
I'm wrote a mail to ecovacs support just to understand if there is some issue in their side. 
It is random today my last clean it is recorded.

Thanks for the help
