### ISSUE TITLE
Resume Area Cleaning after Paused

### ISSUE THREAD

**Issue by timothylarson** [And3rsL/Deebot-for-Home-Assistant#151]
How do I get the Deebot to resume the current cleaning job once paused?

I can call the service:
```
service: vacuum.pause
target:
  entity_id: vacuum.deebot
```
And the Deebot pauses cleaning, but I can't figure out how to resume.

I was doing an area cleaning with just one room, and sent the vacuum.pause service call and it paused, but when I send:
```
service: vacuum.start
target:
  entity_id: vacuum.deebot
```
It starts a new job to auto clean the whole house.

I have tried:
```
service: vacuum.pause
target:
  entity_id: vacuum.deebot
```
```
service: vacuum.start
target:
  entity_id: vacuum.deebot
```
```
service: vacuum.start_pause
target:
  entity_id: vacuum.deebot
```
```
service: vacuum.toggle
target:
  entity_id: vacuum.deebot
```
```
service: vacuum.turn_on
target:
  entity_id: vacuum.deebot
```
```
service: vacuum.resume
target:
  entity_id: vacuum.deebot
```
But nothing works to continue an area cleaning.

**Comment by edenhaus** [comment]
Which version are you using?

**Comment by edenhaus** [comment]
the command `vacuum.start_pause` is supported from 3.0.0b10

**Comment by timothylarson** [comment]
I just checked and I was running version 3.0.0b8, I just upgraded to 3.0.0b11 and it seems to work great. Thank you.

**Comment by edenhaus** [comment]
@timothylarson 
I removed the implementation of command _vacuum.start_pause_ due base class change in 3.0.0b12. The command _vacuum.start_ will resume the cleaning if it was paused, otherwise start a new one.

**Comment by pachi81** [comment]
Hi, 
I´m using version 3.2.1 for my Deebot ozmo 950 and the resume does not work. It always starts auto-cleaning auf pause, if I press the play button.
Do you need any logs?
Regards, Michael
