### ISSUE TITLE
Can't connect my Deebot OZMO T8 AIVI

### ISSUE THREAD

**Issue by adomnits** [And3rsL/Deebot-for-Home-Assistant#153]
Hi
I was able authenticate to my deebot account and even see my robot in the list, but unable to connect it....
I'm able to connect it from Ecovacs application.

**Screenshots**
![image](https://user-images.githubusercontent.com/38213611/124956537-c1354080-e020-11eb-9b02-8df7322d6333.png)

**System Information:**
 - Device: Deebot OZMO T8 AIVI
 - Home Assistant Version: 2021.6.6
 - Hardware: Raspberry PI4
 - Home Assistant Installation: Windows

**Logs**
nothing in the log

**Comment by edenhaus** [comment]
Can you please add the logs. From the screenshot I can see, that an error occurred. So probably something must be in the logs :)

**Comment by edenhaus** [comment]
closing due missing information
