### ISSUE TITLE
I don't see the room numbers

### ISSUE THREAD

**Issue by Veuchez** [And3rsL/Deebot-for-Home-Assistant#156]
**Describe the bug**
I don't see the room numbers and I can't do the spot cleaning anymore

**Screenshots**
![IMG_20210716_140357](https://user-images.githubusercontent.com/59020055/125944666-cc44a948-01fc-4728-83fb-0cd32f2e8151.jpg)

**System Informations:**
 - Device: Deebot ozmo 950
 - Home Assistant Version: 2021.7.3
 - Hardware: VM
 - Home Assistant Installation: Home Assistant OS 6.1

**Additional context**

**Logs**
Please add full home_assistant.log filtered on [deebotozmo, custom_components.deebot, homeassistant.components.vacuum]
If you have multiple vacuums please add the logs only for the relevant one.

**Comment by edenhaus** [comment]
Which version of the component are you using?
Can you please verify with the developers tools. When selecting the vacuum there can you see the rooms?

**Comment by Veuchez** [comment]
Hello,
as you can see from the photo I have attached, unfortunately if I click on the vacuum cleaner, the rooms do not appear.
I use the latest version, 2.1.2.

**Comment by Veuchez** [comment]
![IMG_20210716_172557](https://user-images.githubusercontent.com/59020055/125971692-c222c378-66b3-4d74-b72e-e0c7c343edc5.jpg)

I don't even see them here ..

**Comment by edenhaus** [comment]
Are there rooms shown in the app and is the map saved correctly?
If the robot thinks it's a new map, then it want provide room numbers.

**Comment by Veuchez** [comment]
![IMG_20210716_185957](https://user-images.githubusercontent.com/59020055/125983321-34b4cfb6-f67b-45e2-9816-808ff6e04ec1.jpg)

**Comment by Edo78** [comment]
I'm not sure if it's related but a few days ago the integration for my chinese account wasn't able to retrieve the map (even in the log it's stated something about a new map and the need to map the floor). I restarted HA and the map was succesfully retrieved.
Even the official app continuosly goes in timeout so I think it was a server issue.

@Veuchez have you tried to restart HA?

@edenhaus is there a better way to force the integration to try to get the map again?

**Comment by Veuchez** [comment]
Yes I have restarted home assistant several times but the rooms do not see them ... the map shows them to me, they are the rooms that does not show me ..

**Comment by Veuchez** [comment]
I remapped the house and the rooms appeared, maybe my ozmo had some problem.  Thank you all!
