### ISSUE TITLE
How can I find the coordinates for custom area

### ISSUE THREAD

**Issue by fxcoolby** [And3rsL/Deebot-for-Home-Assistant#184]
### Question

Hello, I am wondering how I can find the coordinates for custom area cleaning, in the app when I  draw an area it only gives me the area in sq ft. Where in the example it looks like the coordinates are in pixels. 

I am trying to take advantage of following service command: 

`# Customize Clean
# You can get coordinates with fiddler and the official APP [Advance User]
entity_id: vacuum.YOUR_ROBOT_NAME
command: custom_area
params:
  coordinates: -1339,-1511,296,-2587`

Thanks a lot!

**Comment by illivanillie** [comment]
Somewhere in the map you have 0x0x0x0.
The individual coordinates stand for one point through which a line (border) will be drawn.
It follows a clock-wise pattern, but I am not sure about which one is first. 
So for example: -200, 500, 1000, -300 == left border at point -200 from zero, upper at 500, right at 1000, lower at -300.
Start with low numbers like -500, 500, 500, -500 so you can estimate the zero point and from there change one number after another to see which order pattern it is exactly.
I hope I was clear enough.

**Comment by mrbungle64** [comment]
@fxcoolby 

You can also try my Node.js library to find out the coordinates for custom area:

https://github.com/mrbungle64/ecovacs-deebot.js/wiki/Retrieve-coordinates-from-log-output#customarea

**Comment by fxcoolby** [comment]
Thanks for all the help, I ended up starting from 0,10,0,10 and changed every coordinate by 200 to see how boundary changes and from there kept changing the numbers untill I got the right area, took a little bit of time but worked.

**Comment by edenhaus** [comment]
The smallest custom area, that my robot accepts is `250x50 (or 50x250)`. Smaller area will not be cleaned and the robot returns automatically to the dock. Only an event (currently events are not supported by this integration) is fired, that the area is blocked.
Also the coordinates are in millimeters and the point `(0,0)` is nearly the charger.

@mrbungle64 Is your lib already handling `onEvt`?

**Comment by mrbungle64** [comment]
@edenhaus 

> @mrbungle64 Is your lib already handling `onEvt`?

No, I never recognized this event. When is this sent?

**Comment by edenhaus** [comment]
With the next update the coordinates of custom areas will be logged on debug level.

@mrbungle64 I created #193 as follow up ticket to handle `onEvt`

**Comment by Maxtropos** [comment]
I use a much more simple method. I use mitmproxy to sniff the app traffic. Install mitmproxy, configure your PCs IP as the proxy on your phone (port 8080). Then start mitmproxy and go to mitm.it to get the HTTPS certificates. Install them accordingly (use the manual, especially on iPhones)

Then just start a cleaning job from the app. You can sniff the coordinates or commands pretty easily from the request of the app.

**Comment by edenhaus** [comment]
@Maxtropos your solution is only working on iPhone or on rooted Android Phones.
