### ISSUE TITLE
how can I enter the water level next to the fan, if available

### ISSUE THREAD

**Issue by RW-7** [And3rsL/Deebot-for-Home-Assistant#186]
### Question

how can I enter the water level next to the fan, if available
![deboot](https://user-images.githubusercontent.com/65983282/131509335-c927f199-dcba-4a7c-ad7e-e19977f557ea.JPG)

**Comment by edenhaus** [comment]
Please ask this question directly in the [vacuum-card](https://github.com/denysdovhan/vacuum-card) as this is card specific (frontend) and has nothing to do with this component.
I know you copied my screenshot from the examples folder, but I don't know if the card supports it and you get more help there.
