### ISSUE TITLE
Can I have your contact?

### ISSUE THREAD

**Issue by Sanguyeenx** [And3rsL/Deebot-for-Home-Assistant#191]
### Question

Can I have your contact? 
Im from Asia, my company want to use Ecovacs T9 modifying to AGV, control on HaSS.
Do you think its impossible? 
ex: deebot go a beeline from A-point to B-point and come back to dock. 
I’d like to use “Spot clean” mode. 
… Can you help me some things? I can pay to you some coffe ^^

### Additional information

sanguyeenx@gmail.com

**Comment by edenhaus** [comment]
Can you please describe it in more details?
I didn‘t understand exactly what do you want to do? What is AGV?

**Comment by Sanguyeenx** [comment]
Can you give me your email for exchange?
My project is to improve the deebot into a "warehouse AGV" robot. Transport goods from one warehouse to another and back to the original location.
I would like your help to tweak the HASS software so that the robot can go to the multi selected point. Is it feasible?

**Comment by edenhaus** [comment]
This integration is only sending command to the deebot vacuum. The firmware on the vacuum is untouched and therefore I don‘t understand how you use it to transport goods.

With HASS you mean Home Assistant?
Also why you need my email address? Can you don‘t post all information here?

**Comment by Sanguyeenx** [comment]
I meant,Can I config at Home Assistant to make Vacuum go from Dock-charge to selected point (clean area = 0)?

**Comment by edenhaus** [comment]
Out of the box there don't exist a command to go to a specific point. But with some tweaks it is possible.
Which model to you want to use it?

**Comment by Sanguyeenx** [comment]
Omg, thank you, I choose t9, can t9 do it? Is it difficult?
Can you help me?

**Comment by edenhaus** [comment]
Search me on [Discord](https://discord.com/)
Username is `edenhaus#4703`

**Comment by edenhaus** [comment]
@Sanguyeenx I wrote you on Discord. T9 is currently not supported but it can be added quite easy, when we handle the new events send from the bot

**Comment by edenhaus** [comment]
@Sanguyeenx I wrote you on Discord.
