### ISSUE TITLE
Deebot Ecovacs 605

### ISSUE THREAD

**Issue by vannetta** [And3rsL/Deebot-for-Home-Assistant#192]
### Question

Hi,
I have @soltroy https://gist.github.com/Soltroy/b3ae9a48f4030e3d00fda22af52723d8 integration for my Deebot 605; it seems only working with this.
I updated the last changes for Python 3.9, but I'm not sure I'll able to do more complicated issues.
I installed your add-on but the Deebot 605 is "unvailable".
Can you suggest me something? Is will be possibile to join it with the one I'm using now?
Thank you so much

**Comment by edenhaus** [comment]
Use instead a gist the custom component https://github.com/Ligio/hacc-ozmo
We do not support your model #35

**Comment by vannetta** [comment]
Thanks!
