### ISSUE TITLE
Not working anymore after upgrading to latest version

### ISSUE THREAD

**Issue by StefanoGiu** [And3rsL/Deebot-for-Home-Assistant#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

ERROR (MainThread) [homeassistant.setup] Setup failed for deebot: Unable to import component: No module named 'deebotozmo.ecovacs_api'

### On which deebot vacuum you have the issue?

Deebot N8

### Which version of the Deebot component are you using?

3.1.3

### Which version of Home Assistant are you using?

2021.9.7

### What type of installation are you running?

Home Assistant Core

### Country

it

### Continent

eu

### Anything in the logs that might be useful for us?

```txt
.Setup failed for deebot: Unable to import component: No module named 'deebotozmo.ecovacs_api'
```

### Additional information

Setup failed for deebot: Unable to import component: No module named 'deebotozmo.ecovacs_api'

**Comment by edenhaus** [comment]
How did you install this component?
Can you please verify that the file `ecovacs_api.py` exists under `[your configuration path]/custom_components/deebot`?

**Comment by StefanoGiu** [comment]
I installed it via HACS. The file is not there...

**Comment by edenhaus** [comment]
Then something with your installation went wrong. Please try to reinstall it.

**Comment by StefanoGiu** [comment]
Re-installed again... file is not coming...

**Comment by StefanoGiu** [comment]
btw this file is not even in Github folder...

**Comment by edenhaus** [comment]
Wait stop... The file exists in the library. Totally confused today.... This means during the installation of the library something went wrong.

Dou you have access to your system and can run `pip uninstall deebotomzo` and then restart HA

**Comment by StefanoGiu** [comment]
C:\Users\stefa>pip uninstall deebotomzo
WARNING: Skipping deebotomzo as it is not installed.

**Comment by edenhaus** [comment]
I mean on the system where Home Assistant is running. Sorry forgotten to clarify it

**Comment by StefanoGiu** [comment]
you mispelled it... that's why... I uninstalled it...

I restarted HA, re-configured the Home Assistant Integration...

now it says: the device is disabled from configuration file...

**Comment by edenhaus** [comment]
I don't understand your last sentence

**Comment by StefanoGiu** [comment]
Fixed it. You can close.

**Comment by edenhaus** [comment]
Next time please close the issue yourself, when it's fixed
