### ISSUE TITLE
Ecovacs Deebot Ozmo 900 (DN5G) Support

### ISSUE THREAD

**Issue by patrickstigler** [And3rsL/Deebot-for-Home-Assistant#199]
### Question

I got an Ecovacs Deebot Ozmo 900 (DN5G) - it is kind of recognized. It will detect the name. Unfortunately nothing else.
I can't control it. 

Could you please add support for it? 
Do you need some information?

**Comment by edenhaus** [comment]
your model is not supported by this component as it uses a different communication protocol. See #35 
Currently I don't plan to add it, but feel free to do it.
