### ISSUE TITLE
Integration both Ozmo 920 - 605

### ISSUE THREAD

**Issue by vannetta** [And3rsL/Deebot-for-Home-Assistant#234]
### Question

Hi,
as you suggested some time ago I installed https://github.com/Ligio/hacc-ozmo in order to work my Deebot 605, and it worked perfectly.
After I bought a Ozmo 920 and I use both; you integration has the same folder that Ligio's one, so when I installed it, it rewrote the Ligio custom components folder.
Do you know if I can solve this problem and integrate both Deebot?
Thanks a lot

**Comment by edenhaus** [comment]
Both custom integration use the same integration name ("deebot") and therefore you cannot use both as the same time.

There are plans to add support for `MQTT/XML` in the future in this integration... But I don't know, when and how long it would take. For sure this will not happen in 2021
