### ISSUE TITLE
Automatic Refresh randomly stops

### ISSUE THREAD

**Issue by martiesim** [And3rsL/Deebot-for-Home-Assistant#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

The automatic refresh of the vacuum's status randomly just stops. All entities for the device are affected, so the status, the map, the battery etc all won't update anymore.

Calling the service to manually refresh does still work though. So this seems to be a workaround for the moment.

### On which deebot vacuum you have the issue?

Deebot Ozmo T8 with added station so it's a T8+ but not really

### Which version of the Deebot component are you using?

Doesn't show in Log, but HACS doesn't show any updates either so probably the latest

### Which version of Home Assistant are you using?

2021.10.6

### What type of installation are you running?

Home Assistant OS

### Country

de

### Continent

eu

### Instance type

Cloud

### Anything in the logs that might be useful for us?

```txt
The following error messages comes up a lot in the log and I only copied the last occurance.
This is also the last message with "deebot" in it.

2021-11-10 15:48:11 ERROR (MainThread) [deebotozmo.ecovacs_mqtt] An exception occurred during handling atr message
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/deebotozmo/ecovacs_mqtt.py", line 113, in _handle_atr
await bot.handle(topic_split[2], data)
File "/usr/local/lib/python3.9/site-packages/deebotozmo/vacuum_bot.py", line 206, in handle
await self.map.handle(
File "/usr/local/lib/python3.9/site-packages/deebotozmo/map.py", line 167, in handle
self._handle_map_sub_set(data)
File "/usr/local/lib/python3.9/site-packages/deebotozmo/map.py", line 233, in _handle_map_sub_set
subtype = int(event_data["subtype"])
KeyError: 'subtype'
```

**Comment by edenhaus** [comment]
> ### On which deebot vacuum you have the issue?
> 
> Deebot Ozmo T8 with added station so it's a T8+ but not really

The version will be logged on info level on startup. I probably have fixed this problem already, but I'm waiting that https://github.com/hacs/default/pull/1119 is merged. As it is not in my hands, I cannot say how long it would take.

**Comment by edenhaus** [comment]
Probably the refresh is stopped after 7 days without a HA restart. Is this correct?

**Comment by martiesim** [comment]
Hi there are no info level output in my log. Do I have to activate that somewhere?
My log starts with a bunch of warnings about me using custom integrations - in fact this is the first line of the log file:
`WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration deebot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant`

The refreshing stopped about 24h after system start.
I left it running this time and used my workaround and the log filled with some more warnings from your integration:
```
WARNING (MainThread)[deebotozmo.commands.base] Command "getCleanInfo" was not successfully: {'ret': 'fail', 'errno': 500, 'debug': 'wait for response timed out'}
```
But that's probably just my polling too often.

**Comment by edenhaus** [comment]
Than your level is probably Warning or Error.
I need debugs logs to help you, please refer to https://github.com/And3rsL/Deebot-for-Home-Assistant#issues

**Comment by edenhaus** [comment]
Closing this issue as now the migration to the replacement component is available. If the issue still exist in the new component, please open a new issue there.
