### ISSUE TITLE
Installed via HACS but not showing up when searching to add integration

### ISSUE THREAD

**Issue by EDIflyer** [And3rsL/Deebot-for-Home-Assistant#246]
### Question

On HA core-2021-11.5, supervised.  HACS 1.18.0
Installed Deebot for HA integration via HACS (v.3.2.1), restarted HA

![image](https://user-images.githubusercontent.com/13610277/144217663-c25af370-e86a-4f20-9865-593724aa6620.png)

However when I then go Config > Integrations > Add and search for Deebot I can't find anything?

![image](https://user-images.githubusercontent.com/13610277/144217624-ea7a6c35-c6cf-4d29-839b-08e593781ca5.png)

I've installed other HACS integrations (e.g., Hildebrand Glow) OK.

**Comment by CPilgram** [comment]
Same Problem for me. Layer 8 Problem or Bug?

**Comment by EDIflyer** [comment]
LOL had to Google that one, but hoping it's not a a PEBCAK issue 😄

**Comment by AlessandroV82** [comment]
Same for me!

**Comment by emansih** [comment]
I manually installed the add on and it appears in integration. 

1. Make a new folder in `custom_components` named deebot
2. Copy the files in this directory
3. Restart Home Assistant

**Comment by EDIflyer** [comment]
I've double checked and the deebot folder is already there for me...

![image](https://user-images.githubusercontent.com/13610277/145681223-9561353b-1f4c-48f8-80d7-e1469038c40f.png)

So installation seems to have gone OK, it's just not working?
