### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by edenhaus** [And3rsL/Deebot-for-Home-Assistant#92]
Some time ago Home Assistant get away from hassio and now everything is called Home Assistant, I would probably change also the name. So for new users it is more clear.
Some examples:
- Deebot for HA
- Deebot for Home Assistant
- Ecovacs Deebot (Completely different but the company dehind is ecovacs)

@And3rsL What do you think?

**Comment by And3rsL** [comment]
👍 
I chose "Deebot for Home Assistant", i think it contains both keywords that people will search on google
